### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by xeno-sun** [warrenburton/RazeMind#3]
Thanks for your excellent tutorial! And would you like to share some advice about enhancing performance for such mind map app with large amount nodes?

I'm a web developer with 4 years experience, familiar with svg / canvas / react techniques. The techniques building mind map app described in the tutorial is so like using react and svg in the web. React and SVG is great for beginning, but will meet performance bottlenecks with large amount nodes, so many mind map apps are building using canvas.

So if I want to develop a mind map app for iOS with large amount nodes and more dynamic effects, is swift + canvas better than swift + UIKit?

**Comment by warrenburton** [comment]
It’s an even choice right now. In theory SwiftUI should handle very large maps but that’s not true in practise. 
I did have an experiment when I was constructing the project for this tutorial where the drawing color for links and nodes was picked randomly on each redraw and the problem was that despite only one element in the array of links or nodes changing everything would get a redraw signal. I would expect the inbuilt diffing algo to just redraw relevant changes.
Also when zoomed in the frame rate was still low which indicates that even the off screen elements were getting redraw computation done. 
Also the inbuilt automatic text internationalisation Gobbles up huge amounts of CPU.
Techniques like using `drawingGroup` didn’t make much difference either.
UIKit on the other hand let’s you cull the offscreen drawing and can use techniques like tiled layers.
I’d say you get better drawing performance with UIKit but it’s more effort to implement. Unless you really have a burning need for very large scale maps I might pick SwiftUI
SwiftUI 2.0 should be out next week and maybe the tables will have turned. One of the big complaints in SwiftUI 1.0 has been performance in large lists and by extension this could extend to off screen drawing.

**Comment by xeno-sun** [comment]
Thanks for your reply!
